name: Build

on: [ push ]

jobs:
  build:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: true

      - name: Build
        run: |
          mkdir build && cmake .. && cmake --build .
        working-directory: tree-sitter/lib

      - name: Upload tree-sitter artifact
        uses: actions/upload-artifact@v4
        with:
          name: tree-sitter-osx
          path: |
            tree-sitter/lib/build/libtree-sitter.dylib
